import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f2f2f7",
  },
  container: {
    flex: 1,
    backgroundColor: "#f2f2f7",
    maxWidth: 414,
    width: "100%",
    alignSelf: "center",
  },
  statusBar: {
    height: 44,
    backgroundColor: "rgba(255,255,255,0.8)",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    borderBottomWidth: 0.5,
    borderBottomColor: "#3c3c4329",
  },
  statusBarTime: {
    fontSize: 17,
    fontWeight: "600",
    color: "#000000",
  },
  statusBarIcons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  navigationBar: {
    height: 44,
    backgroundColor: "rgba(255,255,255,0.8)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: "#3c3c4329",
  },
  navButtonLeft: {
    position: "absolute",
    left: 16,
    padding: 8,
  },
  navButtonText: {
    fontSize: 17,
    fontWeight: "400",
    color: "#007aff",
  },
  navTitle: {
    fontSize: 17,
    fontWeight: "600",
    color: "#000000",
  },
  contentArea: {
    flex: 1,
    paddingBottom: 20,
  },
  bookHeader: {
    backgroundColor: "#4c6ef5",
    padding: 24,
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    position: "relative",
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
  },
  bookImageWrapper: {
    width: 100,
    height: 140,
    backgroundColor: "#5c7cfa",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 32,
    elevation: 8,
  },
  bookImage: {
    width: 100,
    height: 140,
    borderRadius: 12,
  },
  bookInfo: {
    flex: 1,
  },
  bookTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 8,
    lineHeight: 26,
  },
  bookAuthor: {
    fontSize: 16,
    color: "rgba(255,255,255,0.9)",
    marginBottom: 12,
  },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 12,
  },
  star: {
    fontSize: 18,
  },
  ratingValue: {
    fontSize: 16,
    fontWeight: "600",
    color: "#ffffff",
  },
  ratingCount: {
    fontSize: 14,
    color: "rgba(255,255,255,0.8)",
  },
  tagsRow: {
    flexDirection: "row",
    gap: 8,
  },
  tag: {
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    fontSize: 12,
    fontWeight: "600",
    color: "#ffffff",
  },
  tagAvailable: {
    backgroundColor: "#34c75980",
  },
  quickInfoCard: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  quickInfoItem: {
    flex: 1,
    alignItems: "center",
    marginBottom: 0,
  },
  quickInfoValue: {
    fontSize: 20,
    fontWeight: "700",
    color: "#007aff",
    marginBottom: 4,
  },
  quickInfoLabel: {
    fontSize: 12,
    color: "#3c3c4399",
  },
  actionButtonsRow: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 16,
    marginTop: 20,
  },
  buttonSuccess: {
    backgroundColor: "#34c759",
    flex: 1,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  buttonSuccessText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  buttonSecondary: {
    width: 56,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#f2f2f7",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  buttonSecondaryText: {
    fontSize: 16,
  },
  detailsList: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  detailsListItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: "#3c3c4329",
    gap: 12,
  },
  iconCircle: {
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  iconBlue: {
    backgroundColor: "#007aff",
  },
  iconGreen: {
    backgroundColor: "#34c759",
  },
  iconOrange: {
    backgroundColor: "#ff9500",
  },
  iconPurple: {
    backgroundColor: "#af52de",
  },
  iconPink: {
    backgroundColor: "#ff2d92",
  },
  iconRed: {
    backgroundColor: "#ff3b30",
  },
  detailsText: {
    flex: 1,
  },
  detailsLabel: {
    fontSize: 16,
    fontWeight: "500",
    color: "#000000",
  },
  detailsValue: {
    fontSize: 14,
    color: "#3c3c4399",
  },
  descriptionSection: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 20,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  sectionHeader: {
    fontSize: 13,
    fontWeight: "400",
    color: "#3c3c4399",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 16,
  },
  descriptionText: {
    fontSize: 16,
    lineHeight: 24,
    color: "#3c3c43",
  },
  tagsSection: {
    paddingHorizontal: 16,
    marginTop: 20,
  },
  tagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  tagItem: {
    backgroundColor: "#f2f2f7",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  tagText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#007aff",
  },
  reviewsSection: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 20,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  reviewItem: {
    flexDirection: "row",
    gap: 12,
    paddingVertical: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: "#3c3c4329",
  },
  reviewAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  reviewAvatarText: {
    color: "#ffffff",
    fontWeight: "600",
    fontSize: 14,
  },
  reviewContent: {
    flex: 1,
  },
  reviewAuthor: {
    fontSize: 14,
    fontWeight: "500",
    color: "#000000",
    marginBottom: 4,
  },
  reviewRating: {
    color: "#ff9500",
    marginBottom: 4,
  },
  reviewDate: {
    fontSize: 12,
    color: "#3c3c4399",
    marginBottom: 8,
  },
  reviewText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#3c3c43",
  },
  relatedBooksSection: {
    paddingHorizontal: 16,
    marginTop: 20,
  },
  relatedBookItem: {
    width: 120,
    alignItems: "center",
    marginRight: 12,
  },
  relatedBookCover: {
    width: 80,
    height: 110,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 4,
  },
  relatedBookEmoji: {
    fontSize: 32,
  },
  relatedBookTitle: {
    fontSize: 12,
    fontWeight: "500",
    textAlign: "center",
    lineHeight: 16,
    color: "#000000",
    marginBottom: 4,
  },
  relatedBookRating: {
    fontSize: 10,
    color: "#3c3c4399",
  },
});

export default styles;
