import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f2f2f7",
    maxWidth: 414,
    width: "100%",
    alignSelf: "center",
  },
  statusBar: {
    height: 44,
    backgroundColor: "rgba(255,255,255,0.8)",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    borderBottomWidth: 0.5,
    borderBottomColor: "#3c3c4329",
  },
  statusBarTime: {
    fontSize: 17,
    fontWeight: "600",
    color: "#000000",
  },
  statusBarIcons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  navigationBar: {
    height: 44,
    backgroundColor: "rgba(255,255,255,0.8)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: "#3c3c4329",
  },
  navTitle: {
    fontSize: 17,
    fontWeight: "600",
    color: "#000000",
  },
  navButton: {
    padding: 8,
    fontSize: 17,
    fontWeight: "400",
  },
  navButtonText: {
    color: "#007aff",
  },
  filterHeader: {
    backgroundColor: "#ffffff",
    padding: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: "#3c3c4329",
  },
  filterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  filterTabs: {
    flexDirection: "row",
    gap: 8,
  },
  filterTab: {
    backgroundColor: "#f2f2f7",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  filterTabActive: {
    backgroundColor: "#007aff",
  },
  filterTabText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#3c3c43",
  },
  filterTabTextActive: {
    color: "#ffffff",
  },
  sortButton: {
    backgroundColor: "#f2f2f7",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  sortButtonActive: {
    backgroundColor: "#007aff",
  },
  sortButtonText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#3c3c43",
  },
  sortButtonTextActive: {
    color: "#ffffff",
  },
  viewToggle: {
    flexDirection: "row",
    backgroundColor: "#f2f2f7",
    borderRadius: 8,
    padding: 2,
  },
  viewButton: {
    backgroundColor: "transparent",
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  viewButtonActive: {
    backgroundColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  viewButtonText: {
    color: "#3c3c43",
  },
  viewButtonTextActive: {
    color: "#007aff",
  },
  contentArea: {
    flex: 1,
    backgroundColor: "#f2f2f7",
  },
  statsBar: {
    backgroundColor: "#ffffff",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: "#3c3c4329",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  statsText: {
    fontSize: 14,
    color: "#3c3c4399",
  },
  iosList: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    margin: 16,
    overflow: "hidden",
  },
  iosListItem: {
    padding: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: "#3c3c4329",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  iosListItemLast: {
    borderBottomWidth: 0,
  },
  bookCover: {
    width: 60,
    height: 80,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 4,
  },
  bookCoverLarge: {
    width: 80,
    height: 110,
    fontSize: 32,
  },

  gridView: {
    flexDirection: "row",
    flexWrap: "wrap",
    padding: 16,
    gap: 16,
  },

  gridItem: {
    width: "48%",
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  iosBadge: {
    backgroundColor: "#ff3b30",
    color: "#ffffff",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
    fontSize: 12,
    fontWeight: "600",
    minWidth: 20,
    textAlign: "center",
  },
  iosBadgeSuccess: {
    backgroundColor: "#34c759",
  },
  iosBadgeWarning: {
    backgroundColor: "#ff9500",
  },
  loadingSpinner: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
  },
  spinner: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: "#f2f2f7",
    borderTopColor: "#007aff",
    borderRadius: 12,
  },
  loadingText: {
    marginLeft: 12,
    color: "#3c3c4399",
  },
  slideIn: {
    // Animation would be handled by react-native-reanimated or similar
  },
  fadeIn: {
    // Animation would be handled by react-native-reanimated or similar
  },
  // Keep existing styles for compatibility
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 16,
  },
  searchInput: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    padding: 12,
    fontSize: 17,
    marginRight: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  filterButton: {
    backgroundColor: "#007aff",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  filterButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  filtersContainer: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  filterTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#000000",
    marginBottom: 20,
  },
  filterLabel: {
    fontSize: 16,
    fontWeight: "500",
    color: "#000000",
    marginBottom: 12,
  },
  filterChip: {
    backgroundColor: "#f2f2f7",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    marginBottom: 8,
  },
  filterChipSelected: {
    backgroundColor: "#007aff",
  },
  filterChipText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#007aff",
  },
  filterChipTextSelected: {
    color: "#ffffff",
  },
  resultsContainer: {
    flex: 1,
    paddingHorizontal: 16,
  },
  resultsCount: {
    fontSize: 14,
    color: "#3c3c4399",
    marginBottom: 16,
  },
  bookCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    flexDirection: "row",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 0.5,
    borderColor: "#e5e5e7",
  },
  bookImage: {
    width: 70,
    height: 90,
    borderRadius: 12,
    marginRight: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  bookImagePlaceholder: {
    width: 70,
    height: 90,
    backgroundColor: "#f2f2f7",
    borderRadius: 12,
    marginRight: 20,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  bookInfo: {
    flex: 1,
    justifyContent: "space-between",
  },
  bookTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#000000",
    marginBottom: 6,
    lineHeight: 22,
  },
  bookAuthor: {
    fontSize: 15,
    color: "#3c3c4399",
    marginBottom: 4,
    fontWeight: "500",
  },
  bookDetails: {
    fontSize: 13,
    color: "#3c3c4399",
    marginBottom: 6,
    fontWeight: "400",
  },
  bookCategory: {
    fontSize: 13,
    fontWeight: "600",
    color: "#007aff",
    backgroundColor: "#007aff10",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  actionButtonsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  buttonSuccess: {
    backgroundColor: "#34c759",
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: "#34c759",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonSuccessText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  buttonSecondary: {
    backgroundColor: "#f2f2f7",
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 1,
    borderColor: "#e5e5e7",
  },
  buttonSecondaryText: {
    color: "#007aff",
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 50,
  },
  emptyText: {
    fontSize: 20,
    fontWeight: "600",
    color: "#000000",
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 16,
    color: "#3c3c4399",
    textAlign: "center",
    lineHeight: 22,
  },
});

export default styles;
